version: "3.9"

services:
  adguard:
    image: docker.io/adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
      - "3000:3000/tcp"
      - "8000:80/tcp"
      - "8443:443/tcp"
      - "8443:443/udp"
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - proxy
volumes:
  adguard_data:
  adguard_conf:
networks:
  proxy:
    external: true
