version: "3.9"

services:
  taskchampion:
    image: taskchampion-sync-server
    container_name: taskchampion-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - task_data:/var/lib/taskchampion-sync-server/data
    environment:
      - RUST_LOG=debug
    networks:
      - proxy

volumes:
  task_data:
networks:
  proxy:
    external: true
