version: "3.9"

services:
  adguard:
    image: docker.io/adguard/adguardhome:v0.108.0-b.79
    container_name: adguard
    restart: unless-stopped
    volumes:
      - adguard_data:/opt/adguardhome/work
    ports:
      - "5300:53"
    networks:
      - proxy
volumes:
  adguard_data:
networks:
  proxy:
    external: true
