version: "3.9"

services:
  adguard:
    # TODO: fix adguardhome version for DOH
    image: docker.io/adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - adguard_data:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports:
      - "5300:53/udp"
      - "5300:53/tcp"
    networks:
      - proxy
volumes:
  adguard_data:
networks:
  proxy:
    external: true
